# Project: algo3
# Makefile created by Steve Chang
# Date modified: 2024.04.07

LIBNAME = libopt.a

DIR = src

SUBDIR =

INCLUDE =

SRCS = $(wildcard *.c)

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
