# Project: algo3
# Makefile created by Steve Chang
# Date modified: 2024.02.25

LIBNAME = libmain.a

DIR = src

SUBDIR =

INCLUDE = \
	crc \
	mutex \
	utility \
	thread \

SRCS = $(wildcard *.c)

OBJDIR = obj

include $(MAKE_RULES)
